version: '3.x'

services:

  hogbridge:
    image: dreamkhv/hogbridge
    container_name: hogbridge
    ports:
      - '1025:1025'
      - '8025:8025'
      - '8080:8080'
    environment:
      SERVER_PORT: ':8080'
      MAIL_HOST: localhost
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
